BASE_OID = "1.3.6.1.4.1.99999"

ALARM_TRAP = BASE_OID + ".1"
LOW_BATTERY_TRAP = BASE_OID + ".2"
DEAD_BATTERY_TRAP = BASE_OID + ".3"
NODE_FAILURE_TRAP = BASE_OID + ".4"

ALARM_TRAP_NODE = ALARM_TRAP + ".1"
ALARM_TRAP_SEV = ALARM_TRAP + ".2"
ALARM_TRAP_MSG= ALARM_TRAP + ".3"

LOW_BATT_NODE = LOW_BATTERY_TRAP + ".1"
LOW_BATT_SEV = LOW_BATTERY_TRAP + ".2"
LOW_BATT_BATT = LOW_BATTERY_TRAP + ".3"

DEAD_BATT_NODE = DEAD_BATTERY_TRAP + ".1"
DEAD_BATT_SEV = DEAD_BATTERY_TRAP + ".2"
DEAD_BATT_BATT = DEAD_BATTERY_TRAP + ".3"

FAIL_NODE = NODE_FAILURE_TRAP + ".1"
FAIL_SEV = NODE_FAILURE_TRAP + ".2"
FAIL_BATT = NODE_FAILURE_TRAP + ".3"
FAIL_MSG = NODE_FAILURE_TRAP + ".4"